# Generated by Django 2.2.13 on 2021-03-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='signiature',
            new_name='signature',
        ),
        migrations.AddField(
            model_name='candidate',
            name='Recommendation_count',
            field=models.IntegerField(default=0),
        ),
    ]
